//! Per-creator catalog system.
//!
//! Catalogs are derived from an append-only event log under
//! `creators/{creator_id}/events/`. On every publish, a new event is appended
//! (with a conditional write so concurrent publishes don't lose events) and
//! the creator's `catalog/latest.json` is regenerated by reading the full
//! event log. A versioned snapshot is written alongside `latest.json` for
//! rollback and audit.
//!
//! Design rules from the development plan:
//! - No database.
//! - No continuous builder.
//! - Regenerate only the affected creator's catalog on publish.

pub mod keys;
pub mod publish;
pub mod types;

pub use types::*;

use serde_json::Value;

/// Build the canonical catalog from an ordered list of publish events.
///
/// "Canonical" means: the same set of events produces the same catalog bytes
/// regardless of input order. Specifically:
///
/// - Dedupe by `content_id`: keep the highest-`seq` event per content_id.
///   Re-publishing the same content_id replaces its catalog entry.
/// - Sort entries by `published_at` descending (ties broken by seq desc).
/// - `version` is the maximum seq across all events (or 0 if empty).
///
/// The `generated_at` and `signature` are filled in by callers that produce
/// the serialized form (see [`finalize_catalog`]).
pub fn build_catalog(creator_id: &str, mut events: Vec<PublishEvent>) -> CatalogDraft {
    events.sort_by_key(|e| e.seq);

    let version = events.last().map(|e| e.seq).unwrap_or(0);

    let mut latest_per_content: std::collections::HashMap<String, PublishEvent> =
        std::collections::HashMap::new();
    for event in events {
        latest_per_content.insert(event.content_id.clone(), event);
    }

    let mut entries: Vec<(u64, CatalogEntry)> = latest_per_content
        .into_values()
        .map(|e| (e.seq, e.entry))
        .collect();

    entries.sort_by(|a, b| {
        b.1.published_at
            .cmp(&a.1.published_at)
            .then_with(|| b.0.cmp(&a.0))
    });

    CatalogDraft {
        creator_id: creator_id.to_string(),
        version,
        entries: entries.into_iter().map(|(_, e)| e).collect(),
    }
}

/// A catalog without `generated_at` or `signature`. Pure function of the
/// event set, suitable for unit testing.
#[derive(Debug, Clone)]
pub struct CatalogDraft {
    pub creator_id: String,
    pub version: u64,
    pub entries: Vec<CatalogEntry>,
}

impl CatalogDraft {
    /// Attach a timestamp and placeholder signature to produce a complete
    /// [`Catalog`].
    pub fn finalize(self, generated_at: String) -> Catalog {
        let unsigned = serde_json::json!({
            "creator_id": self.creator_id,
            "version": self.version,
            "generated_at": generated_at,
            "entries": self.entries,
        });
        let signature = sign_placeholder(&unsigned);
        Catalog {
            creator_id: self.creator_id,
            version: self.version,
            generated_at,
            entries: self.entries,
            signature,
        }
    }
}

/// Placeholder signing: BLAKE3 digest of the canonical JSON body.
///
/// This is not cryptographically authenticated — it only detects accidental
/// tampering. The eventual replacement is ed25519 over the same bytes.
pub fn sign_placeholder(body: &Value) -> CatalogSignature {
    let canonical = canonical_json(body);
    let digest = blake3::hash(canonical.as_bytes());
    CatalogSignature {
        method: "blake3-unsigned-placeholder".to_string(),
        value: digest.to_hex().to_string(),
    }
}

/// Serialize a JSON value deterministically: object keys in lexicographic
/// order, no insignificant whitespace. Used as the signing input so the
/// signature is reproducible.
fn canonical_json(value: &Value) -> String {
    let mut buf = String::new();
    write_canonical(value, &mut buf);
    buf
}

fn write_canonical(value: &Value, out: &mut String) {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        Value::Number(n) => out.push_str(&n.to_string()),
        Value::String(s) => {
            // serde_json::to_string handles the escaping for us
            out.push_str(&serde_json::to_string(s).expect("string serializes"));
        }
        Value::Array(items) => {
            out.push('[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                write_canonical(item, out);
            }
            out.push(']');
        }
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            out.push('{');
            for (i, k) in keys.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                out.push_str(&serde_json::to_string(k).expect("key serializes"));
                out.push(':');
                write_canonical(&map[*k], out);
            }
            out.push('}');
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_event(seq: u64, content_id: &str, published_at: &str) -> PublishEvent {
        PublishEvent {
            seq,
            creator_id: "creator_1".to_string(),
            content_id: content_id.to_string(),
            kind: PublishEventKind::Publish,
            published_at: published_at.to_string(),
            entry: CatalogEntry {
                content_id: content_id.to_string(),
                creator_id: "creator_1".to_string(),
                title: format!("title-{}", seq),
                visibility: Visibility::Public,
                required_tier_ids: vec![],
                tdf_ref: format!("iroh:{}", content_id),
                manifest_ref: format!(
                    "s3://creators/creator_1/content/{}/manifest.json",
                    content_id
                ),
                published_at: published_at.to_string(),
            },
        }
    }

    #[test]
    fn empty_event_log_yields_empty_catalog_version_zero() {
        let draft = build_catalog("creator_1", vec![]);
        assert_eq!(draft.version, 0);
        assert!(draft.entries.is_empty());
    }

    #[test]
    fn republishing_content_id_replaces_entry_keeps_latest_seq() {
        let events = vec![
            make_event(1, "content_a", "2026-05-25T10:00:00Z"),
            make_event(2, "content_b", "2026-05-25T11:00:00Z"),
            make_event(3, "content_a", "2026-05-25T12:00:00Z"),
        ];
        let draft = build_catalog("creator_1", events);
        assert_eq!(draft.version, 3);
        assert_eq!(draft.entries.len(), 2);
        let a = draft
            .entries
            .iter()
            .find(|e| e.content_id == "content_a")
            .unwrap();
        assert_eq!(a.title, "title-3");
    }

    #[test]
    fn entries_sorted_by_published_at_descending() {
        let events = vec![
            make_event(1, "content_a", "2026-05-25T10:00:00Z"),
            make_event(2, "content_b", "2026-05-26T10:00:00Z"),
            make_event(3, "content_c", "2026-05-24T10:00:00Z"),
        ];
        let draft = build_catalog("creator_1", events);
        let ids: Vec<&str> = draft.entries.iter().map(|e| e.content_id.as_str()).collect();
        assert_eq!(ids, vec!["content_b", "content_a", "content_c"]);
    }

    #[test]
    fn build_catalog_is_input_order_independent() {
        let a = make_event(1, "content_a", "2026-05-25T10:00:00Z");
        let b = make_event(2, "content_b", "2026-05-26T10:00:00Z");
        let forward = build_catalog("c", vec![a.clone(), b.clone()]);
        let reverse = build_catalog("c", vec![b, a]);
        let f = forward.finalize("2026-05-25T00:00:00Z".to_string());
        let r = reverse.finalize("2026-05-25T00:00:00Z".to_string());
        assert_eq!(f.signature.value, r.signature.value);
    }

    #[test]
    fn signature_changes_when_entries_change() {
        let one = build_catalog("c", vec![make_event(1, "a", "2026-05-25T10:00:00Z")])
            .finalize("2026-05-25T00:00:00Z".to_string());
        let two = build_catalog(
            "c",
            vec![
                make_event(1, "a", "2026-05-25T10:00:00Z"),
                make_event(2, "b", "2026-05-25T11:00:00Z"),
            ],
        )
        .finalize("2026-05-25T00:00:00Z".to_string());
        assert_ne!(one.signature.value, two.signature.value);
    }

    #[test]
    fn canonical_json_sorts_object_keys() {
        let v = serde_json::json!({"b": 1, "a": 2, "c": [3, 2, 1]});
        assert_eq!(canonical_json(&v), r#"{"a":2,"b":1,"c":[3,2,1]}"#);
    }
}
